---
driver:
  name: vagrant
  synced_folders: 
  - ["~/shuttle","/home/vagrant/shuttle"]
  - ["~/work/polymer","/home/vagrant/polymer"]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["private_network", {ip: "192.168.33.44"}]

suites:
  - name: dfdevm_polymer
    run_list:
      - recipe[dfdevm_polymer::default]
    attributes:
