---
driver:
  name: vagrant
  synced_folders: 
  - ["~/shuttle","/opt/shuttle"]

provisioner:
  name: chef_zero

platforms:
- name: box-cutter-VAGRANTSLASH-ubuntu1404-desktop
  driver_config:
    box: box-cutter-VAGRANTSLASH-ubuntu1404-desktop
    box_url: ~/Vagrant\ boxes/box-cutter-VAGRANTSLASH-ubuntu1404-desktop

suites:
  - name: dfdevm_polymer
    run_list:
      - recipe[dfdevm_polymer::default]
    attributes:
