name 'dfdevm_polymer'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dfdevm_polymer'
long_description 'Installs/Configures dfdevm_polymer'
version '0.1.0'

depends 'git'
depends 'nodejs'
depends 'df_node_fix'
